import { type NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { events, type TEvent } from "~/constants/events";
import { AppContext } from "~/context";

const Home: NextPage = () => {
  const { data } = useContext(AppContext);

  const handleEventPick = () => {
    const events = document.querySelectorAll(".game-event");
    console.log({ events });
    for (const event of events) {
      event.classList.remove("!bg-teal-700");
    }

    const index = Math.floor(Math.random() * (events.length - 1));
    events[index]?.classList.add("!bg-teal-700");
  };

  const handleEventClick = (event: TEvent) => {
    alert(event.description);
  };

  return (
    <>
      <Head>
        <title>Merchants </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"
        style={{
          backgroundImage: "url('/images/merchants-bg.jpg')",
          backgroundSize: "cover",
        }}
      >
        <div className="flex h-full w-full  grow  flex-col items-center justify-start bg-black/30 p-6 backdrop-blur-[1px]">
          <div className=" flex flex-col items-center justify-center">
            <div className="text-shadow-3 font-[sign45] text-7xl font-bold tracking-tighter text-white">
              MERCHANTS
            </div>
            <div className="mt-[-7px] text-sm font-semibold text-white">
              Board Game by Yuri Garcia
            </div>
          </div>
          {data.permission === "admin" && (
            <div
              className=" mt-12 overflow-auto rounded-md bg-indigo-500 px-6 py-2 font-[sign45] text-4xl text-white"
              onClick={handleEventPick}
            >
              gerar evento
            </div>
          )}
          <div className="my-12 grid grid-cols-2 gap-4 bg-indigo-500/70 p-2">
            {events.map((e, index) => {
              return (
                <div
                  className="game-event flex flex-row items-center gap-2 rounded-md bg-gray-800 px-4 py-1 font-[sign45] text-white"
                  key={index}
                  onClick={() => handleEventClick(e)}
                >
                  <div className="">{e.icon}</div>
                  <div className="w-full text-end">{e.name}</div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
